name: 'Docker image to GCP Aritfact using Github actions'

on:
  push:
    branches: 
    - 'main'
    
jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' 

      - name: 'install the gcloud cli'
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
  
      - name: 'build and push the docker image'
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}
          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/python_flask_app:latest ./flask_app
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/python_flask_app:latest 
          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/flask_app_sql_database:latest ./db
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/flask_app_sql_database:latest


          
